apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-deploy
  namespace: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
        - name: devops-demo
          image: nghiant2005/devops-demo:171a04ba15bc93f06258420aa24e4bd46b18ead2
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
